modal
Lara-E/SitHub pull request #24
Opened 2019-05-15 21:44 UTC by loubeants

2019-05-15 21:51 UTC, kyang0626 approved these changes
still some conflicts!

2019-05-15 21:54 UTC, dumpstro requested changes
Hey Lou, 
Lara changed the html files to handlebars so you'll need to move these files into their handlebar versions. 
If you need to add anything to the html head, it's the main.handlebars file in the layout folder.

2019-05-16 15:16 UTC, kyang0626 approved these changes
good to go

2019-05-16 15:18 UTC, dumpstro approved these changes

2019-05-16 15:19 UTC, merged